name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout code 
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build . --file Dockerfile \
          --tag ghcr.io/${{ github.repository }}:${{ steps.tag_version.outputs.new_tag }} \
          --tag ghcr.io/${{ github.repository }}:latest

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}:${{ steps.tag_version.outputs.new_tag }}
        docker push ghcr.io/${{ github.repository }}:latest
