name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code 
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:${{ github.sha }} && docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
