name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code 
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Podman
      run: |
        sudo apt-get update
        sudo apt-get -y install podman

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push podman image
      run: |
        podman build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:${{ github.sha }}
        podman push ghcr.io/${{ github.repository }}:${{ github.sha }}
